# Generated by Django 5.0 on 2023-12-20 23:06

import analytical.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('reload_count_in_a_clock', models.IntegerField(default=1)),
                ('ip_address', models.TextField()),
                ('ip_data', models.JSONField(blank=True, default=analytical.models.default_ip_data, null=True)),
                ('is_i_am', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, default=None, editable=False, null=True)),
            ],
        ),
    ]
