# Generated by Django 4.2.8 on 2024-01-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmodel',
            name='query_string',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='viewmodel',
            name='request_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='viewmodel',
            name='request_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
