# Generated by Django 4.2.8 on 2024-01-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0002_viewmodel_query_string_viewmodel_request_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmodel',
            name='http_sec_ch_ua',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
