# Generated by Django 5.0.3 on 2024-03-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0003_viewmodel_http_sec_ch_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmodel',
            name='time_tick_count',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
