# Generated by Django 5.0.3 on 2024-09-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0004_viewmodel_time_tick_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_host', models.CharField(max_length=150)),
                ('platform_path', models.TextField(default='')),
                ('media_source', models.TextField(default='')),
                ('view', models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel')),
            ],
        ),
    ]
