# Generated by Django 5.0.3 on 2024-09-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0005_analyticmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticmedia',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='analyticmedia',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
