# Generated by Django 5.0.3 on 2024-09-12 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0006_analyticmedia_slug_analyticmedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analyticmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
