# Generated by Django 5.1.1 on 2024-12-31 12:28

import config.custom_fields.encrypted_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0009_anormalhttplogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='ip_address',
            field=config.custom_fields.encrypted_field.EncryptedField(),
        ),
    ]
