# Generated by Django 5.1.1 on 2024-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0010_alter_viewmodel_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmodel',
            name='ip_address',
            field=models.TextField(),
        ),
    ]
