# Generated by Django 4.2.8 on 2024-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_contentcommentmodel_contentmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
