# Generated by Django 4.2.8 on 2024-02-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0003_viewmodel_http_sec_ch_ua'),
        ('projects', '0004_contentmodel_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel'),
        ),
    ]
