# Generated by Django 4.2.8 on 2024-02-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_contentmodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='content', to='projects.contentcommentmodel'),
        ),
    ]
