# Generated by Django 4.2.8 on 2024-02-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_contentmodel_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmodel',
            old_name='ceo_description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='contentmodel',
            old_name='ceo_image_alt',
            new_name='seo_image_alt',
        ),
        migrations.RenameField(
            model_name='contentmodel',
            old_name='ceo_image_url',
            new_name='seo_image_url',
        ),
    ]
