# Generated by Django 5.0.3 on 2024-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_ceo_description_contentmodel_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='seo_image_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
