# Generated by Django 5.0.3 on 2024-04-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_contentmodel_seo_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmodel',
            options={'ordering': ('title',)},
        ),
    ]
