# Generated by Django 5.0.3 on 2024-04-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_contentmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodel',
            name='language_type',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Türkçe')], default='1', max_length=1),
        ),
    ]
