# Generated by Django 5.0.3 on 2024-05-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_contentmodel_language_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcommentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='contentcommentmodel',
            name='email',
            field=models.EmailField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contentcommentmodel',
            name='name',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
