# Generated by Django 5.0.3 on 2024-05-01 13:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_contentcommentmodel_sender_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
