# Generated by Django 5.0.3 on 2024-05-15 03:35

import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_contentmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodel',
            name='slug',
            field=projects.models.TurkishAutoSlugField(always_update=True, blank=True, editable=True, populate_from='title', unique=True),
        ),
    ]
