# Generated by Django 5.1.1 on 2024-12-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_contentmodel_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentcommentmodel',
            old_name='sender_agent',
            new_name='view',
        ),
    ]
