# Generated by Django 5.1.1 on 2024-12-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_sender_agent_contentcommentmodel_view'),
        ('tags', '0002_tagcategorymodel_order_alter_tagcategorymodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypemodel',
            name='sub_tags',
            field=models.ManyToManyField(related_name='content_types', to='tags.tagmodel'),
        ),
    ]
