# Generated by Django 5.1.1 on 2024-12-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_contenttypemodel_sub_tags'),
        ('tags', '0002_tagcategorymodel_order_alter_tagcategorymodel_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttypemodel',
            name='sub_tags',
            field=models.ManyToManyField(blank=True, related_name='content_types', to='tags.tagcategorymodel'),
        ),
    ]
