# Generated by Django 5.0 on 2023-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='disable_ceo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='image_alt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
