# Generated by Django 5.0 on 2023-12-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_pagemodel_disable_ceo_alter_pagemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextFieldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('field_type', models.CharField(choices=[('1', 'MD'), ('2', 'List'), ('3', 'img')], default='1', max_length=2)),
                ('field_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.ManyToManyField(to='pages.contextfieldmodel')),
            ],
        ),
    ]
