# Generated by Django 5.0 on 2023-12-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contextfieldmodel_contextmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='context',
            field=models.ManyToManyField(to='pages.contextfieldmodel'),
        ),
        migrations.DeleteModel(
            name='ContextModel',
        ),
    ]
