# Generated by Django 5.0 on 2023-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0001_initial'),
        ('pages', '0004_pagemodel_context_delete_contextmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemodel',
            name='view',
            field=models.ManyToManyField(to='analytical.viewmodel'),
        ),
    ]
