# Generated by Django 5.0 on 2023-12-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0001_initial'),
        ('pages', '0005_pagemodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemodel',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, editable=False, to='analytical.viewmodel'),
        ),
    ]
