# Generated by Django 5.0 on 2023-12-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0001_initial'),
        ('pages', '0006_alter_pagemodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextfieldmodel',
            name='name',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='view',
            field=models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel'),
        ),
    ]
