# Generated by Django 5.0 on 2023-12-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_contextfieldmodel_name_alter_pagemodel_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextfieldmodel',
            name='field_type',
            field=models.CharField(choices=[('1', 'MD'), ('2', 'List'), ('3', 'img'), ('4', 'text')], default='1', max_length=2),
        ),
    ]
