# Generated by Django 5.0 on 2023-12-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_pagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextfieldmodel',
            name='field_type',
            field=models.CharField(choices=[('1', 'MD'), ('2', 'List'), ('3', 'img'), ('4', 'text'), ('5', 'html')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='pagemodel',
            name='image',
            field=models.TextField(blank=True, default=None),
        ),
    ]
