# Generated by Django 5.0.3 on 2024-04-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_navbaritemmodel_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagemodel',
            options={'ordering': ('title',)},
        ),
    ]
