# Generated by Django 5.0.3 on 2024-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todomodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='detail',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
