# Generated by Django 5.1.1 on 2025-01-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallmodel',
            old_name='message',
            new_name='wall',
        ),
        migrations.RemoveField(
            model_name='wallmodel',
            name='title',
        ),
    ]
