# Generated by Django 5.0 on 2023-12-23 13:44

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='otpmodel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
