# Generated by Django 5.0 on 2023-12-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_alter_otpmodel_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='hash_gen',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='otp_device',
            field=models.TextField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
