# Generated by Django 5.0 on 2023-12-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_remove_otpmodel_hash_gen_otpmodel_otp_device'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='otpmodel',
            managers=[
            ],
        ),
    ]
