# Generated by Django 4.2.8 on 2024-01-30 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('icon_type', models.CharField(choices=[('1', 'FA'), ('2', 'image')], default='1', max_length=1)),
                ('icon', models.TextField(blank=True, default=None, help_text='when call (fa/src) use this refs', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tags.tagcategorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='tagcategorymodel',
            name='tags',
            field=models.ManyToManyField(to='tags.tagmodel'),
        ),
    ]
