# Generated by Django 4.2.8 on 2024-01-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programinglanguagemodel',
            name='icon',
            field=models.TextField(help_text='when call (fa/src) use this refs'),
        ),
    ]
