# Generated by Django 4.2.8 on 2024-02-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategorymodel',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tagcategorymodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tagmodel'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='icon_type',
            field=models.CharField(choices=[('1', 'FA'), ('2', 'image'), ('3', 'None')], default='3', max_length=1),
        ),
    ]
