# Generated by Django 4.2.8 on 2024-01-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tagmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategorymodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.tagmodel'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='icon',
            field=models.TextField(blank=True, help_text='when call (fa/src) use this refs'),
        ),
    ]
