# Generated by Django 4.2.8 on 2024-02-17 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_manager', '0001_initial'),
        ('tags', '0002_tagcategorymodel_order_alter_tagcategorymodel_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.URLField(blank=True, default=None, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('length', models.PositiveBigIntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('banner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_manager.mediamodel')),
                ('tags', models.ManyToManyField(blank=True, to='tags.tagmodel')),
            ],
        ),
    ]
