# Generated by Django 4.2.8 on 2024-02-17 08:45

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytical', '0003_viewmodel_http_sec_ch_ua'),
        ('tags', '0002_tagcategorymodel_order_alter_tagcategorymodel_tags_and_more'),
        ('media_manager', '0001_initial'),
        ('projects', '0006_alter_contentmodel_comments'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('show', models.BooleanField(default=True)),
                ('seo_description', models.CharField(max_length=500)),
                ('seo_image_url', models.TextField(blank=True, default=None)),
                ('seo_image_alt', models.TextField(blank=True, null=True)),
                ('description', models.TextField(max_length=350)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, related_name='game_videos', to='projects.contentcommentmodel')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.contenttypemodel')),
                ('tags', models.ManyToManyField(to='tags.tagmodel')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_manager.mediamodel')),
                ('view', models.ManyToManyField(blank=True, default=None, to='analytical.viewmodel')),
            ],
        ),
    ]
