# Generated by Django 4.2.8 on 2024-02-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_manager', '0001_initial'),
        ('game', '0002_gamevideomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamevideomodel',
            name='seo_image_url',
        ),
        migrations.AddField(
            model_name='gamevideomodel',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gameinfomodel'),
        ),
        migrations.AddField(
            model_name='gamevideomodel',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.musicinfomodel'),
        ),
        migrations.AlterField(
            model_name='gamevideomodel',
            name='video',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='media_manager.mediamodel'),
        ),
    ]
