# Generated by Django 5.0.3 on 2024-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamevideomodel_seo_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinfomodel',
            name='game_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
