# Generated by Django 5.0.3 on 2024-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='mail',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='contact',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.contactmodel'),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='job_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='picture',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
