# Generated by Django 5.0.3 on 2024-05-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_projectexperiencesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='right_side',
            field=models.TextField(default=''),
        ),
    ]
