# Generated by Django 5.0.3 on 2024-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_prt'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperiencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('experience', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='resumemodel',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, default=None, to='resume.workexperiencesmodel'),
        ),
        migrations.DeleteModel(
            name='PRT',
        ),
    ]
