# Generated by Django 5.0.3 on 2024-04-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_contactmodel_mail_alter_contactmodel_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='github',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='linkedin',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
