# Generated by Django 5.0.3 on 2024-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resumemodel_right_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexperiencesmodel',
            name='row',
            field=models.IntegerField(default=0),
        ),
    ]
