# Generated by Django 5.0.3 on 2024-04-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_workexperiencesmodel_resumemodel_work_experiences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperiencesmodel',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
