# Generated by Django 5.0.3 on 2024-05-16 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_projectexperiencesmodel_row'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexperiencesmodel',
            options={'ordering': ('row',)},
        ),
    ]
