# Generated by Django 5.0.3 on 2024-06-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_projectexperiencesmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexperiencesmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
