# Generated by Django 5.0.3 on 2024-07-11 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='')),
                ('token', models.UUIDField(default=uuid.UUID('c7f13912-24d1-47d9-ad5b-95729f97cbac'))),
                ('token_expr', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
