# Generated by Django 5.0.3 on 2024-08-09 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_platform_alter_surveyuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='choice',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.choice'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='icon',
            field=models.ImageField(upload_to='platform'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.UUIDField(default=uuid.UUID('d64cbf85-74cd-46d9-8341-d8794bc0b332')),
        ),
    ]
