# Generated by Django 5.0.3 on 2024-09-11 05:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_response_choice_alter_platform_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.UUIDField(default=uuid.UUID('6432c9be-9fd9-4e77-a693-b4b4c64ca272')),
        ),
    ]
