# Generated by Django 5.0.3 on 2024-09-11 06:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_surveyuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.UUIDField(default=uuid.UUID('5aafd6f3-2cd9-48cb-936c-2436664955ec')),
        ),
    ]
