# Generated by Django 5.0.3 on 2024-09-12 07:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_surveyuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='token',
            field=models.UUIDField(default=uuid.UUID('8163f4f7-1673-49a1-8c98-a5c07e9c9fec')),
        ),
    ]
